### ISSUE TITLE
FL bonuses do not work

### ISSUE THREAD

**Issue by hrdys** [sherrifjack1/AME-Calculator#2]
FL bonuses do not work for any race.

**Comment by sherrifjack1** [comment]
That's because another function didn't work, it has something to do with
the way players type in their inputs. I'll have a look at it.

**Comment by sherrifjack1** [comment]
It's because you typed the race in lowercase letters but this has been resolved for your convenience.

**Comment by sherrifjack1** [comment]
Resolved
