### ISSUE TITLE
"the First unit"

### ISSUE THREAD

**Issue by hrdys** [sherrifjack1/AME-Calculator#3]
![image](https://user-images.githubusercontent.com/43370627/140579513-36d78f1a-b7f8-4052-bba4-87ee16e3d361.png)

**Comment by hrdys** [comment]
Also, there is no way to enter the unit's quantity

**Comment by sherrifjack1** [comment]
Unity Quantity is actually renamed as Unity Amount

So after they ask you the cost, they then as you the amount of units
present.

The type of units is there to present how many types of units u have like
whether u have

Merc Cav
And Mirkwood Units

Or just Mirkwood Units.
And if you got Mirkwood Units do you have all 3 types of them or just one
or two.

**Comment by sherrifjack1** [comment]
Yeah this happened because a function didn't work, I'll look into it.

**Comment by sherrifjack1** [comment]
issue resolved.
